### ISSUE TITLE
Question regarding intrinsic reward bonus implementation

### ISSUE THREAD

**Issue by mch5048** [younggyoseo/apv#1]
Hi, thanks for sharing this amazing work!

I have a question regarding the intrinsic reward bonus out of blue while reading the code implementation.

In the code implementation and as mentioned in the paper, the intrinsic bonus that incentivizes exploration is computed 
from the trajectories samples from the "experienced/replay buffer-sampled" data. The bonus term is added to the extrinsic reward value to train the reward predictor as the Dreamer does.

In the imagination phase, the model should predict the sum of extrinsic and intrinsic rewards to compute the return value for actor-critic learning, and it encourages the agent to explore unvisited states.

In my opinion, the intrinsic bonus doesn't have to be learned by the reward predictor but can be computed directly from imagined trajectories since the z_{t:t+\tau} required for computing intrinsic values are sampled from prior distribution during imagination phase.  
(actually I am also working on the extension work of DreamerV2 that computes intrinsic bonus, and in my project I am doing like so.)

I wonder if you have tried computing the intrinsic bonus in this manner or if there's my misunderstanding of your work.

Thanks in advance and I am happy to find that someone in South Korea is also interested in the world-model based robot control problems. Hope I can share my work to you soon.

**Comment by younggyoseo** [comment]
Thanks for your interest in our work!
- Regarding the implementation, your understanding is correct in that our implementation computes intrinsic bonus using the videos from a replay buffer.
- Regarding the next question - I prefer to discuss this kind of research-related things via e-mail as Issue is more related to the implementation and computes. Could you close the issue and send me an e-mail? Then we can discuss on this there.

**Comment by mch5048** [comment]
Thanks for the quick prompt. I'll close this issue and contact you via email.
