### ISSUE TITLE
pre-training data

### ISSUE THREAD

**Issue by zhanglixuan0720** [younggyoseo/apv#6]
Hi! I noticed that in the released training dataset, the pre-training data from triped_walk only includes 73 videos with a total of 36,573 frames, which is different from the 1,000 videos mentioned in the paper. Will the complete pre-training data from triped_walk be released?

**Comment by younggyoseo** [comment]
Hi, I uploaded a full set of npzs yesterday, could you check it? 

Best,
Younggyo

**Comment by zhanglixuan0720** [comment]
> Hi, I uploaded a full set of npzs yesterday, could you check it?
> 
> Best, Younggyo

Yes,  I have checked the uploaded dataset. 
It's ok now. Thank you!
